models/Products.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "Products".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $photo
 * @property integer $price
 * @property integer $category
 * @property string $main
 */
class Products extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Products';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'photo', 'price', 'category', 'main'], 'required'],
            [['name', 'description', 'main'], 'string'],
            [['price', 'category'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'photo' => 'Photo',
            'price' => 'Price',
            'category' => 'Category',
            'main' => 'Main',
        ];
    }

    public function getCategories()
    {
        return $this->hasOne(Category::className(), ['id' => 'category']);
    }

    public function getCategoryValue()
    {
        return $this->categories->translation;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Products;
use app\models\Category;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $get = Yii::$app->request->get();
        if (!empty($get['cat'])){
            $products = Products::find()->where(['category' => $get['cat']])->all();
        } else {
            if (isset($get['all'])) {
                $products = Products::find()->all();
            } else {
                $products = Products::find()->all();
            }
        }
        return $this->render('index', [
            'products' => $products
        ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays a single Products model.
     * @param integer $id
     * @return mixed
     */
    public function actionProduct($id)
    {
        $model = Products::findOne($id);
        return $this->render('product', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Products model.
     * @param integer $id
     * @return mixed
     */
    public function actionCategory($id) //scorn
    {
        $model = Category::findOne($id);
        return $this->render('category', [
            'model' => $model,
        ]);
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use \yii\helpers\Url;
use \app\models\Products;
use \yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */

$this->title = 'Коракс. Надежный партнер';
?>
<div class="container content">
    <div class="content_main">
        <div class="header-slogan">
            Продажа и адаптация<br/> программных продуктов <span style="color: #f2bf00;">1С</span> <br/>в
            Ростовской Области
        </div>

        <div class="actions" id="actions_block">
            <span class="title">Акции</span>

            <div class="left">
                <div class="logo"></div>
                <span>Бесплатная установка</span>
                При покупке любой конфигурации 1С версии ПРОФ наши специалисты приедут, бесплатно установят и
                запустят в
                эксплуатацию базу данных (установка, настройка базы и настройка резервного копирования).
            </div>
            <div class="right">
                <div class="logo"></div>
                <span>Бесплатная помощь</span>
                Специалист нашей компании подъедет к Вам в офис в удобное время, проведет тестирование базы данных,
                ответит на любой вопрос по ведению учета в 1С, а также обучит ваших сотрудников пользованию системой
                1С
                Информационно - Технологическое Сопровождение (ИТС).
            </div>
        </div>

        <div class="actions" id="catalog_block">
            <span class="title">Каталог</span>
            <?php Pjax::begin(); ?>
            <div class="col-lg-12 col-md-12">
                <div class="cat-mnu">
                    <ul>
                        <li>
                            <?= Html::a('Все продукты', ['site/index', 'all' => true]) ?>
                        </li>
                        <? $categories = \app\models\Category::find()->all();?>
                        <? foreach ($categories as $category) : ?>
                        <li>
                            <?= Html::a($category->translation, ['site/index', 'cat' => $category->id]) ?>
                        </li>
                        <? endforeach; ?>
                    </ul>
                </div>
            </div>
            <div class="cat-list">
                <? foreach ($products as $product) : ?>
                <div class="cat-product" onclick="location.href = '<?= Url::to(['site/product', 'id' => $product->id]);?>'">
                    <div class="cat"><?= $r = $product->categoryValue; ?></div>
                    <div class="img"><?= Html::img('@web/img/catalog/'.$product->photo, ['alt'=>Yii::$app->name]); ?></div>
                    <div class="name"><?= $product->name; ?></div>
                    <div class="price"><?= $product->price; ?> &#8381;</div>
                </div>
                <? endforeach; ?>
            </div>
            <?php Pjax::end(); ?>
        </div>

        <div class="actions" id="uslugi_block">
            <span class="title">Услуги</span>

            <div class="service">
                <div class="logo"
                     style="background-image: url(../../img/SystemReport.png); background-repeat: no-repeat; background-position: center; position: relative"></div>
                <span>Информационно-технологическое сопровождение 1с</span>
                Вся линейка программных продуктов 1С постоянно обновляется и модифицируется. Будьте в курсе всех
                возможностей своей версии! Воспользуйтесь нашими услугами, чтобы установленные программы всегда
                отвечали
                необходимым требованиям и позволяли использовать новые функции.
            </div>
            <div class="service">
                <div class="logo"
                     style="background-image: url(../../img/OnlineSupport.png); background-repeat: no-repeat; background-position: center; position: relative"></div>
                <span>Консультации</span>
                Обратившись к специалистам нашей бесплатной линии консультаций, Вы всегда получите быстрый и
                квалифицированный ответ. Сотрудники компании в любой момент готовы выехать к Вам в офис для решения
                самых неотложных вопросов, требующих внимания профессионала!
            </div>
            <div class="service">
                <div class="logo"
                     style="background-image: url(../../img/Support.png); background-repeat: no-repeat; background-position: center; position: relative"></div>
                <span>Настройка и доработка программных продуктов 1с</span>
                Работа каждой фирмы имеет свою специфику. Наши специалисты готовы настроить Вашу программу так,
                чтобы
                она учитывала все Ваши потребности на 100%. Мы работаем с любыми конфигурациями и выполняем любые
                работы
                по настройке и доработке программных продуктов 1С.
            </div>
        </div>

        <div class="actions" style="margin-bottom: 70px;" id="contacts_block">
            <span class="title">Контакты</span>

            <div class="content">
                <div class="col-md-3">
                    <div class="img_contacts">
                        <?= Html::img('@web/img/Message.png', ['alt'=>Yii::$app->name]); ?>
                    </div>
                    support@koraks-rostov.ru<br/>
                    director@koraks-rostov.ru<br/>
                    manager@koraks-rostov.ru
                </div>
                <div class="col-md-3">
                    <div class="img_contacts">
                        <?= Html::img('@web/img/MapMarker.png', ['alt'=>Yii::$app->name]); ?>
                    </div>
                    г. Ростов-на-Дону<br/>
                    ул. Социалистическая 88,<br/>
                    офис 606
                </div>
                <div class="col-md-3">
                    <div class="img_contacts">
                        <?= Html::img('@web/img/Time.png', ['alt'=>Yii::$app->name]); ?>
                    </div>
                    Пн-пт — 9:00-18:00,<br/>
                    Сб, вс — выходной
                </div>
                <div class="col-md-3">
                    <div class="img_contacts">
                        <?= Html::img('@web/img/Phone.png', ['alt'=>Yii::$app->name]); ?>
                    </div>
                    +7 (863) 279-91-63
                </div>
            </div>
        </div>
    </div>
</div>

<script>

</script>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>


</div>

views/site/product.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Products */

$this->title = $model->name;
?>
<div class="products-view">

    <div class="container content">
        <div class="content_product">
            <div class="row">
                <div class="col-md-12">
                    <div class="cat"><?= $model->categoryValue; ?></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <?= Html::img('@web/img/catalog/'.$model->photo, ['alt'=>Yii::$app->name, "class" => "img-product"]); ?>
                    <div class="question_block">
                        <span class="head">Есть вопросы?</span>
                        <span class="text">Мы всегда с радостью проконсультируем вас!</span>
                        <span class="phone">+7 (863) 279-91-63</span>
                    </div>
                </div>
                <div class="col-md-8" style="font-family: PTSans;">
                    <h3>
                        <?= $model->name; ?>
                    </h3>
                    <div class="price"><?= $model->price; ?> &#8381;</div>
                    <p class="description_product">
                        <?= nl2br($model->description); ?>
<!--                        "1С:Управление торговлей 8" автоматизирует следующие направления хозяйственной деятельности:-->
                    </p>
<!--                    <ul>-->
<!--                        <li>- управление отношениями с клиентами,</li>-->
<!--                        <li>- управление правилами продаж,</li>-->
<!--                        <li>- управление процессами продаж:</li>-->
<!--                        <li>- управление торговыми представителями,</li>-->
<!--                        <li>- управление запасами,</li>-->
<!--                        <li>- управление закупками,</li>-->
<!--                        <li>- управление складом,</li>-->
<!--                        <li>- управление доставкой товаров,</li>-->
<!--                        <li>- управление финансами,</li>-->
<!--                        <li>- контроль и анализ целевых показателей деятельности предприятия.</li>-->
<!--                    </ul>-->
                </div>
            </div>
            <div class="actions" style="margin-bottom: 70px;">
                <span class="title">Контакты для заказа продукта</span>

                <div class="content">
                    <div class="col-md-3">
                        <div class="img_contacts">
                            <?= Html::img('@web/img/Message-gray.png', ['alt'=>Yii::$app->name]); ?>
                        </div>
                        support@koraks-rostov.ru<br/>
                        director@koraks-rostov.ru<br/>
                        manager@koraks-rostov.ru
                    </div>
                    <div class="col-md-3">
                        <div class="img_contacts">
                            <?= Html::img('@web/img/Map-gray.png', ['alt'=>Yii::$app->name]); ?>
                        </div>
                        г. Ростов-на-Дону<br/>
                        ул. Социалистическая 88,<br/>
                        офис 606
                    </div>
                    <div class="col-md-3">
                        <div class="img_contacts">
                            <?= Html::img('@web/img/Time-gray.png', ['alt'=>Yii::$app->name]); ?>
                        </div>
                        Пн-пт — 9:00-18:00,<br/>
                        Сб, вс — выходной
                    </div>
                    <div class="col-md-3">
                        <div class="img_contacts">
                            <?= Html::img('@web/img/Phone-gray.png', ['alt'=>Yii::$app->name]); ?>
                        </div>
                        +7 (863) 279-91-63
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>